In [69]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [70]:
data = pd.read_csv('drug_discovery_virtual_screening.csv')
data

compound_id protein_id  molecular_weight      logp  h_bond_donors  \
0      CID_00000    PID_361        499.671415  2.487233              1   
1      CID_00001    PID_165        436.173570  3.283222              3   
2      CID_00002    PID_168        514.768854       NaN              2   
3      CID_00003    PID_226        602.302986  3.038058              0   
4      CID_00004    PID_224        426.584663  0.659578              2   
...          ...        ...               ...       ...            ...   
1995   CID_01995    PID_425        557.015024  3.542686              4   
1996   CID_01996    PID_100        447.347874  0.383282              1   
1997   CID_01997    PID_265        361.812535  3.019553              0   
1998   CID_01998    PID_125        433.693304  5.965067              0   
1999   CID_01999    PID_296        375.509736  4.040972              5   

      h_bond_acceptors  rotatable_bonds  polar_surface_area  compound_clogp  \
0                    7                4          113.350817        4.050696   
1                    4                4           71.981132        3.704408   
2                   11               11           83.936307        1.869610   
3                    5                5           79.868125        2.451909   
4                    4                5           88.198676        1.771936   
...                ...              ...                 ...             ...   
1995                 5               11          102.329688        1.470121   
1996                 8                5           52.321214        3.739447   
1997                 4                9           86.722469        3.122027   
1998                 4               10           86.932238        3.866579   
1999                 4                2           70.823536        2.002131   

      protein_length  protein_pi  hydrophobicity  binding_site_size  mw_ratio  \
0                678    6.019657        0.812534          12.512165  0.736978   
1                876    6.447408        0.651417          11.538420  0.497915   
2                658    3.925837        0.633467          13.155702  0.782323   
3                312    7.597056        0.513038          12.071822  1.930458   
4               1418    4.249454        0.613571          15.850448  0.300835   
...              ...         ...             ...                ...       ...   
1995             240    7.862185        0.770925          21.308909  2.320896   
1996             718    7.401501        0.644721          16.578658  0.623047   
1997            1228    5.551238        0.717044          16.829751  0.294636   
1998            1244    5.680128        0.661245          10.604194  0.348628   
1999             845    7.022004        0.624876          15.931453  0.444390   

      logp_pi_interaction  binding_affinity  active  
0               14.972288          5.996665       0  
1               21.168271          6.445742       0  
2                9.074061          5.689583       0  
3               23.080293          6.043438       0  
4                2.802846          4.845055       0  
...                   ...               ...     ...  
1995            27.853256          7.209850       1  
1996             2.836864          9.029696       1  
1997            16.762259          5.728118       0  
1998            33.882348          7.324152       1  
1999            28.375721          7.542772       1  

[2000 rows x 17 columns]

In [71]:
X = data.drop(columns=['compound_id', 'protein_id', 'active'])
y = data['active']

In [72]:
numerical_cols = X.columns.tolist()

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numerical_cols)
])

X_processed = preprocessor.fit_transform(X)

In [73]:
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
}

In [74]:
print("Résultats:\n")
for name, model in models.items():
    scores = cross_val_score(model, X_processed, y, cv=5, scoring='accuracy')
    print(name)
    print(scores.mean())
    print(scores.std())
    print(scores)

Résultats:

Logistic Regression
0.984
0.008154753215150055
[0.9875 0.97   0.995  0.985  0.9825]
Decision Tree
1.0
0.0
[1. 1. 1. 1. 1.]
Random Forest
1.0
0.0
[1. 1. 1. 1. 1.]
XGBoost
0.9970000000000001
0.0036742346141747737
[1.     1.     0.9975 0.9975 0.99  ]


C:\Users\darla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xgboost\training.py:183: UserWarning: [21:51:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\darla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xgboost\training.py:183: UserWarning: [21:51:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\darla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xgboost\training.py:183: UserWarning: [21:51:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } 

In [75]:
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', model)
])

pipeline.fit(X, y)

C:\Users\darla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xgboost\training.py:183: UserWarning: [21:51:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['molecular_weight', 'logp',
                                                   'h_bond_donors',
                                                   'h_bond_acceptors',
                                                   'rotatable_bonds',
                                                   'polar_surface_area',
                                                   'compound_clogp',
                                                   'protein_length',
                                                   'protein_pi',
                                                   'hydrophobicity',
                                                   'binding_site_size',
                                                   'mw_ratio',
                                                   'logp_pi_...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [ ]:
new_data = pd.DataFrame([{
    'molecular_weight': 350.0,
    'logp': 3.2,
    'h_bond_donors': 2,
    'h_bond_acceptors': 6,
    'rotatable_bonds': 4,
    'polar_surface_area': 75.0,
    'compound_clogp': 2.9,
    'protein_length': 400,
    'protein_pi': 6.5,
    'hydrophobicity': 0.2,
    'binding_site_size': 120,
    'mw_ratio': 0.875,
    'logp_pi_interaction': 0.3,
    'binding_affinity': -8.5
}])

print("Prédictions sur les nouvelles données :\n")
for name, pipeline in preprocessor:
    prediction = preprocessor.predict(new_data)[0]
    proba = preprocessor.predict_proba(new_data)[0][1] if hasattr(model.named_steps['classifier'], 'predict_proba') else "N/A"
    print(name)
    print(f"  Prédiction: {'Active' if prediction == 1 else 'Inactive'}")
    print(f"  Probabilité d'être active: {proba}\n")

Prédictions sur les nouvelles données :



KeyError: "'0' is not a valid transformer name"